#pragma once

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <iostream>
#include <string>
#include <sstream>
#include <fstream>
#include <vector>
#include <time.h>
#include <math.h>
#include <codecvt>
#include <Psapi.h>
#include <list>
#include <wchar.h>
#include <tchar.h>
#include <conio.h>
#include <stdio.h>
#include <stdlib.h>
#include <ostream>
#include <regex>
#include <winuser.h>
#include <WinReg.h>
#include <winternl.h>
#include <TlHelp32.h>
#include <random>
#include <ctime>
#include <commdlg.h>

#include "Utils/xor.h"
#include "Utils/crt.h"
#include "Utils/spoof.h"
#include "Utils/lw_http.hpp"
#include "Defines.h"
#include "utils.h"
#include "Structs.h"
#include "API.h"
#include "MenuFramework.h"